CREATE TABLE EMP_COPY 
   AS SELECT *
      FROM EMP;
      
      
--1) 전체 조회
SELECT EMPNO, ENAME, JOB, HIREDATE
   FROM EMP_COPY ec;
   
--2) 상세조회
SELECT EMPNO, ENAME, JOB, HIREDATE
   FROM EMP_COPY ec
   WHERE EMPNO='7369';

--3) 입력
INSERT INTO EMP_COPY ex (EMPNO, ENAME, JOB, HIREDATE)
   VALUES('0522', 'JOBS', 'IT', SYSDATE);
   
--4) 수정
UPDATE EMP_COPY
   SET JOB='DEVELOPER'
   WHERE EMPNO = '0522';
   
--5) 삭제
DELETE FROM EMP_COPY ex
   WHERE EMPNO = '0522';
