-- MERGE
-- 하나의 쿼리에 INSERT, UPDATE, DELETE를 작업할 경우
-- MERGE를 통해 여러 개의 쿼리를 하나로 수행

CREATE TABLE EMP_MERGE AS SELECT * FROM EMP;
SELECT *
	FROM EMP_MERGE 
	WHERE EMPNO='3366';
	
-- 만약에 EMPNO가 있다면 -> UPDATE 
-- 							없다면 -> INSERT

MERGE
	INTO EMP_MERGE e
			USING DUAL
			ON(e.EMPNO='3366')
		WHEN MATCHED THEN
			UPDATE 
				SET e.COMM = '1000'
		WHEN NOT MATCHED THEN
			INSERT (EMPNO, ENAME, DEPTNO)
				VALUES('3366','DONG', 10);
				
SELECT COMM
	FROM EMP_MERGE 
	WHERE EMPNO='7499';
	
SELECT *
	FROM EMP_MERGE 
	WHERE EMPNO='3366';
	
--MERGE
--	INTO PLAYER p 
--		USING TEAM t
--		ON (p.TEAM_ID=t.TEAM_ID AND p.PLAYER_ID='77')
--	WHEN MATCHED THEN
--		 --쿼리
--	WHEN NOT MATCHED THEN
--		 --쿼리;
	
MERGE 
	INTO EMP_MERGE em
		USING DUAL
		ON(em.EMPNO='7788')
	WHEN MATCHED THEN 
		UPDATE
			SET em.DEPTNO=10
			WHERE em.JOB='ANALYST'
		DELETE 
			WHERE em.JOB = 'ANALYST';
			
SELECT *
	FROM EMP_MERGE 
	WHERE EMPNO='7788';