-- 선수 요약 조회
-- 팀명, 등번호, 선수이름, 영어이름
-- 1) 전체 조회
-- 2) 팀별 조회
-- 3) 포지션별 조회
-- 4) 이름 OR 백넘버 검색 -> 프로시저

-- 선수 상세 조회
-- 팀명, 등번호, 선수이름, 영어이름, 포지션, 생년월일, 키, 몸무게, 국적

-- 경기 일정 조회
-- 날짜, 경기장명, 홈팀, 홈팀스코어, 원정팀, 원정팀스코어
-- 경기 안함 -> 스코어 보이고, 경기 함 -> 스코어 안보임
-- 1) 일자별 조회
-- 2) 팀별 조회

-- 팀 순위 조회
-- 등수, 팀명, 승점차, 승률

-- 팀 등록, 수정, 삭제
-- 선수 등록, 수정, 삭제
-- 경기 등록, 수정, 삭제
-- 경기 수정시 -> 순위 테이블 변경

-- 선수
SELECT PLAYER_ID , PLAYER_NAME , UPPER(E_PLAYER_NAME)  AS E_PLAYER_NAME , TEAM_ID , "POSITION" , BACK_NO , NVL(NATION, '대한민국') AS NATION , BIRTH_DATE , HEIGHT , WEIGHT  
	FROM PLAYER;

-- 팀
SELECT TEAM_ID , REGION_NAME , TEAM_NAME , ORIG_YYYY , STADIUM_ID , HOMEPAGE
	FROM TEAM;

-- 경기장
(SELECT STADIUM_ID , s.STADIUM_NAME AS STADIUM_NAME , HOMETEAM_ID , SEAT_COUNT , t.ZIP_CODE1 AS ZIP_CODE1 , t.ZIP_CODE2 AS ZIP_CODE2 , t.ADDRESS AS ADDRESS , t.DDD AS DDD , t.TEL AS TEL , t.FAX AS FAX 
	FROM STADIUM s JOIN TEAM t
	USING(STADIUM_ID)) AS STADIUM;
	
-- 일정
SELECT STADIUM_ID , SCHE_DATE , GUBUN , HOMETEAM_ID , AWAYTEAM_ID , HOME_SCORE , AWAY_SCORE 
	FROM SCHEDULE;
	
-- 순위(TEAM_RANK, DIFF 는 추후 계산)
CREATE TABLE LEAGUE_RANK(
	TEAM_ID CHAR(3) CONSTRAINT LEAGUE_RANK_PK PRIMARY KEY,
	NUMBER_OF_GAMES NUMBER(3,0),
	VICTORY NUMBER(3,0),
	TIE NUMBER(3,0),
	LOSS NUMBER(3,0),
	WINNING_RATE NUMBER(4,1)
);

DROP TABLE LEAGUE_RANK;

SELECT *
	FROM LEAGUE_RANK;

DROP TABLE LEAGUE_RANK ;

INSERT INTO LEAGUE_RANK(TEAM_ID, NUMBER_OF_GAMES, VICTORY, TIE, LOSS, WINNING_RATE, DIFF)
	VALUES();
	
SELECT *
	FROM SCHEDULE s2 
	WHERE HOMETEAM_ID = 'K06'
	ORDER BY GUBUN DESC;

SELECT HOMETEAM_ID , COUNT(*)
	FROM SCHEDULE s 
	WHERE GUBUN = 'Y'
	GROUP BY HOMETEAM_ID;
	
SELECT
	HOMETEAM_ID AS TEAM_ID,
	COUNT(*) AS NUMBER_OF_GAMES,
	COUNT(CASE WHEN HOME_SCORE > AWAY_SCORE THEN 1 END) AS VITORY,
	COUNT(CASE WHEN HOME_SCORE = AWAY_SCORE THEN 1 END) AS TIE,
	COUNT(CASE WHEN HOME_SCORE < AWAY_SCORE THEN 1 END) AS LOSS,
	ROUND(COUNT(CASE WHEN HOME_SCORE > AWAY_SCORE THEN 1 END)/COUNT(*), 3) AS WINNING_RATE
	FROM SCHEDULE
	WHERE GUBUN='Y'
	GROUP BY HOMETEAM_ID ;