CREATE TABLE TEST1(COL NUMBER);
CREATE TABLE TEST2(COL NUMBER);
CREATE TABLE TEST3(COL NUMBER);

INSERT INTO TEST1 VALUES(1);
INSERT INTO TEST1 VALUES(2);
INSERT INTO TEST1 VALUES(3);
INSERT INTO TEST1 VALUES(4);
INSERT INTO TEST1 VALUES(5);
INSERT INTO TEST1 VALUES(6);

INSERT INTO TEST2 VALUES(3);
INSERT INTO TEST2 VALUES(7);
INSERT INTO TEST2 VALUES(8);

INSERT INTO TEST3 VALUES(4);
INSERT INTO TEST3 VALUES(5);
INSERT INTO TEST3 VALUES(6);

SELECT * FROM TEST1
UNION ALL
SELECT * FROM TEST2
MINUS
SELECT * FROM TEST3;