SELECT * 
	FROM EMP e ;
SELECT *
	FROM DEPT d ;
SELECT *
	FROM SALGRADE s ;
	
-- 1일차
-- 1번
SELECT EMPNO, ENAME
	FROM EMP e 
	WHERE EMPNO IN ('7369', '7698');
	
-- 2번
SELECT EMPNO, ENAME
	FROM EMP e 
	WHERE NOT EMPNO IN ('7369', '7698');
	
-- 3번
SELECT *
	FROM EMP e 
	WHERE SAL BETWEEN 3000 AND 5000;
	
-- 4번
SELECT *
	FROM EMP e 
	WHERE HIREDATE > '1981-12-01';
	
-- 5번
SELECT MAX(EMPNO)
	FROM EMP e 
	WHERE JOB='SALESMAN';
	
-- 2일차
-- 1번
SELECT DNAME, e.EMPNO, ENAME
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
	ORDER BY DNAME, ENAME;
	
-- 2번
SELECT DNAME, e.EMPNO, ENAME
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
UNION
SELECT NULL, e.EMPNO, ENAME
	FROM EMP e 
	WHERE DEPTNO IS NULL
	ORDER BY DNAME, ENAME;
	
-- 3번
SELECT LOC, EMPNO, ENAME
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
	WHERE LOC IN ('DALLAS', 'CHICAGO')
	ORDER BY LOC DESC, ENAME;

-- 4번
SELECT DEPTNO, MAX(SAL) SAL
	FROM EMP e 
	WHERE DEPTNO IS NOT NULL
	GROUP BY DEPTNO
	ORDER BY DEPTNO;
	
-- 5번
SELECT e2.DEPTNO, e2.SAL, EMPNO, ENAME, JOB
	FROM EMP e  JOIN (SELECT DEPTNO, MAX(SAL) SAL
									FROM EMP e 
									WHERE DEPTNO IS NOT NULL
									GROUP BY DEPTNO) e2
	ON e2.SAL = e.SAL
	ORDER BY DEPTNO;

SELECT DEPTNO, SAL, EMPNO, ENAME, JOB
	FROM EMP e 
	WHERE (e.DEPTNO , SAL) IN (SELECT DEPTNO, MAX(SAL)
													FROM EMP e2 
													GROUP BY DEPTNO	)
	ORDER BY DEPTNO;
	
-- 3일차
-- 1번
SELECT EMPNO, ENAME, SAL, GRADE 
	FROM EMP e JOIN SALGRADE s 
	ON SAL BETWEEN s.LOSAL AND s.HISAL 
	ORDER BY s.GRADE ;
	
-- 2번
SELECT EMPNO, ENAME, JOB, SAL
	FROM EMP e,( SELECT AVG(e2.SAL) AVG
								FROM EMP e2) e3
	WHERE e.SAL > e3.AVG
	ORDER BY SAL DESC;

SELECT EMPNO , ENAME , JOB , SAL 
	FROM EMP e 
	WHERE SAL > (SELECT AVG(SAL)
													FROM EMP e2)
	ORDER BY SAL DESC;

-- 3번
SELECT DNAME, EMPNO, ENAME, JOB, SAL
	FROM EMP e, DEPT d ,(SELECT DEPTNO, AVG(SAL) AVG
									FROM EMP e2 
									GROUP BY DEPTNO) e3
	WHERE	e.DEPTNO = d.DEPTNO 
		AND e.DEPTNO = e3.DEPTNO
		AND SAL > e3.AVG
	ORDER BY SAL DESC;

-- 4번
SELECT GRADE , LOSAL , HISAL , COUNT(*)
	FROM EMP e JOIN SALGRADE s 
	ON SAL BETWEEN s.LOSAL AND s.HISAL 
	GROUP BY (GRADE , LOSAL, HISAL);

-- 5번
SELECT DNAME,LOC, EMPNO, ENAME
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
	WHERE DNAME = 'RESEARCH'
		OR LOC = 'NEW YORK'
	ORDER BY DNAME;

-- 4일차
-- 1번
SELECT *
	FROM EMP e ;





