SELECT * 
	FROM EMP e ;
SELECT *
	FROM DEPT d ;
SELECT *
	FROM SALGRADE s ;
	
-- 1일차
-- 1번
SELECT EMPNO, ENAME
	FROM EMP e 
	WHERE EMPNO IN ('7369', '7698');
	
-- 2번
SELECT EMPNO, ENAME
	FROM EMP e 
	WHERE NOT EMPNO IN ('7369', '7698');
	
-- 3번
SELECT *
	FROM EMP e 
	WHERE SAL BETWEEN 3000 AND 5000;
	
-- 4번
SELECT *
	FROM EMP e 
	WHERE HIREDATE > '1981-12-01';
	
-- 5번
SELECT MAX(EMPNO)
	FROM EMP e 
	WHERE JOB='SALESMAN';
	
-- 2일차
-- 1번
SELECT DNAME, e.EMPNO, ENAME
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
	ORDER BY DNAME, ENAME;
	
-- 2번
SELECT DNAME, e.EMPNO, ENAME
	FROM EMP e JOIN DEPT d 
	ON e.DEPTNO = d.DEPTNO 
	ORDER BY DNAME, ENAME;
	
-- 3번
SELECT LOC, EMPNO, ENAME
	FROM EMP e JOIN DEPT d 
	USING(DEPTNO)
	WHERE LOC IN ('DALLAS', 'CHICAGO')
	ORDER BY LOC DESC, ENAME;

-- 4번
SELECT DEPTNO, MAX(SAL) SAL
	FROM EMP e 
	GROUP BY DEPTNO
	ORDER BY DEPTNO;
	
-- 5번
SELECT DEPTNO, MAX(SAL) SAL
	FROM EMP e 
	GROUP BY DEPTNO ;
	
SELECT e2.DEPTNO, e2.SAL, EMPNO, ENAME, JOB
	FROM EMP e  JOIN (SELECT DEPTNO, MAX(SAL) SAL
									FROM EMP e 
									GROUP BY DEPTNO) e2
	ON e2.SAL = e.SAL
	ORDER BY DEPTNO;