SELECT t.TEAM_NAME, p.*
	FROM PLAYER p JOIN TEAM t 
	ON t.TEAM_ID = p.TEAM_ID ;
	
SELECT (SELECT AVG(HEIGHT) FROM PLAYER p ) AS 평균키, p.*
	FROM PLAYER p ;
	
CREATE TABLE INFOMATION(
	EMP_NO CHAR(1) NOT NULL,
	BIRTH_DATE DATE,
	FIRST_NAME VARCHAR2(40),
	LAST_NAME VARCHAR2(50),
	GENDER CHAR(1),
	HIRE_DATE DATE
);

ALTER TABLE INFOMATION
	ADD CONSTRAINT "infomation_pk"
	PRIMARY KEY(EMP_NO);

SELECT TABLE_NAME, INDEX_NAME
	FROM USER_INDEXES;
	
SELECT ROWNUM AS PLAYER_EXAM, p2.*
	FROM PLAYER p2 JOIN (SELECT TEAM_ID, PLAYER_ID
															FROM PLAYER p 
															ORDER BY 1 DESC) p3
	ON p2.PLAYER_ID =p3.PLAYER_ID;

SELECT ROWNUM PLAYER_EXAM, p.*
	FROM PLAYER p 
	ORDER BY TEAM_ID DESC;


CREATE VIEW PLAYER_VIEW 
	AS SELECT p.*, ROWNUM rn 
				FROM PLAYER p 
				ORDER BY HEIGHT DESC;
				
SELECT * 
	FROM PLAYER_VIEW
	WHERE rn < 10;

SELECT NVL(d.DNAME, 'ALL DEPARTMENTS') AS DNAME , NVL(e.JOB, 'ALL JOBS') AS JOB, COUNT(*), SUM(SAL) 
	FROM EMP e JOIN DEPT d 
	ON e.DEPTNO =d.DEPTNO 
	GROUP BY ROLLUP(d.DNAME, e.JOB);
	
SELECT e.*,
	RATIO_TO_REPORT(SAL) OVER(PARTITION BY DEPTNO)  
	FROM EMP e 
	WHERE DEPTNO=10;
	
CREATE TABLE 상품(
	상품코드 CHAR(4) CONSTRAINT 상품_PK PRIMARY KEY,
	상품명 VARCHAR2(20) NOT NULL,
	제조자 VARCHAR2(50),
	소비자가격 NUMBER,
	재고수량 NUMBER DEFAULT 0
);

CREATE TABLE 입고(
	입고번호 NUMBER CONSTRAINT 입고_PK PRIMARY KEY,
	상품코드 CHAR(4) CONSTRAINT 입고_FK REFERENCES 상품(상품코드),
	입고일자 DATE DEFAULT SYSDATE,
	입고수량 NUMBER,
	입고단가 NUMBER,
	입고금액 NUMBER
);

CREATE SEQUENCE 입고_SEQ
	START WITH 1
	INCREMENT BY 1 NOCYCLE NOCACHE;

INSERT INTO 상품(상품코드, 상품명, 제조자, 소비자가격)
	VALUES('a001', '마우스', '삼성', 1000);
INSERT INTO 상품(상품코드, 상품명, 제조자, 소비자가격)
	VALUES('a002', '키보드', 'LG', 2000);
INSERT INTO 상품(상품코드, 상품명, 제조자, 소비자가격)
	VALUES('a003', '모니터', '알파스켄', 5000);

SELECT *
	FROM 상품;

DELETE FROM 상품;

SELECT *
	FROM 입고;
	
CREATE OR REPLACE TRIGGER 상품_AUTO
	AFTER 
		INSERT ON 입고
	FOR EACH ROW 
	BEGIN 
		UPDATE 상품
			SET 재고수량 = 재고수량 + :NEW.입고수량
			WHERE 상품코드= :NEW.상품코드;
END;

INSERT INTO 입고(입고번호, 상품코드, 입고수량, 입고단가, 입고금액)
	VALUES(입고_SEQ.NEXTVAL, 'a003', 2, 1000, 2000);

CREATE OR REPLACE TRIGGER 상품_UPDATE
	AFTER 
		UPDATE ON 입고
	FOR EACH ROW 
	BEGIN 
		UPDATE 상품
			SET 재고수량 = 재고수량 - :OLD.입고수량 + :NEW.입고수량
			WHERE 상품코드= :NEW.상품코드
				AND 입고일자= :NEW.입고일자;
END;

SELECT *
	FROM 입고;

UPDATE 입고 SET 입고수량=3
	WHERE 상품코드='a003'
		AND 입고일자='2023-06-13 12:27:04.000';

	
SELECT *
	FROM 입고
	WHERE 상품코드='a003'
		AND 입고일자=TO_DATE('2023-06-13 12:27:04');

SELECT *
	FROM DEPT;
	
CREATE OR REPLACE PROCEDURE PL_DEPT_INSERT
(
   V_DEPTNO IN NUMBER,
   V__D_NAME IN VARCHAR2,
   V_LOC IN VARCHAR2,
   V_RESULT OUT VARCHAR2
)
IS
   CNT NUMBER :=0;
BEGIN
   SELECT COUNT(*) INTO CNT
      FROM DEPT d 
      WHERE DEPTNO = V_DEPTNO;
IF CNT>0 THEN
   V_RESULT:= '등록된 부서입니다';
ELSE
   INSERT INTO DEPT(DEPTNO, DNAME, LOC)
      VALUES(V_DEPTNO, V_DNAME, V_LOC);
   COMMIT;
   V_RESULT:= '입력완료';
END IF;
EXCEPTION
   WHEN OTHERS THEN 
   ROLLBACK
   V_RESULT:= 'ERROR';
END;

CREATE OR REPLACE PROCEDURE DEPT_INSERT
(
	V_DEPTNO IN NUMBER,
	V_DNAME IN VARCHAR2,
	V_LOC IN VARCHAR2,
	V_RESULT OUT VARCHAR2
)
IS
	CNT NUMBER:=0;
BEGIN
	SELECT COUNT(*) INTO CNT
	FROM DEPT d 
	WHERE DEPTNO = V_DEPTNO;
IF CNT > 0 THEN
	V_RESULT:='등록된 부서입니다';
ELSE
	INSERT INTO DEPT(DEPTNO, DNAME, LOC)
		VALUES(V_DEPTNO, V_DNAME, V_LOC);
	COMMIT;
	V_RESULT:='입력완료';
END IF;
EXCEPTION
	WHEN OTHERS THEN
	ROLLBACK;
	V_RESULT:='ERROR';
END;

SELECT *
	FROM 입고;
	
SELECT *
	FROM 상품;
	
CREATE OR REPLACE TRIGGER 상품_INSERT
	AFTER
		INSERT ON 입고
	FOR EACH ROW
	BEGIN
		UPDATE 상품
			SET 재고수량 = 재고수량 + :NEW.입고수량
				WHERE 상품코드 = :NEW.상품코드;
	END;
	
INSERT INTO 입고(입고번호, 상품코드, 입고일자, 입고수량, 입고단가, 입고금액)
	VALUES(입고_SEQ.NEXTVAL, 'a001', '2023-06-16', 3, 1000, 3000);
	
SELECT *
	FROM 상품;

SELECT *
	FROM 입고;

DELETE FROM 입고;
DELETE FROM 상품;

	
CREATE OR REPLACE TRIGGER 상품_UPDATE
	AFTER 
		UPDATE ON 입고
	FOR EACH ROW
	BEGIN
		UPDATE 상품
			SET 재고수량 = 재고수량 - :OLD.입고수량 + :NEW.입고수량
				WHERE 상품코드 = :NEW.상품코드;
	END;

UPDATE 입고 SET 입고수량=5
	WHERE 상품코드 = 'a001'
		AND 입고일자='2023-06-16';
			
SELECT *
	FROM 상품;
SELECT *
	FROM 입고
	WHERE 입고일자='2023-06-16';
	
	
CREATE OR REPLACE TRIGGER 상품_DELETE
	AFTER
		DELETE ON 입고
	FOR EACH ROW
	BEGIN
		UPDATE 상품
			SET 재고수량 = 재고수량 - :OLD.입고수량
				WHERE 상품코드 = :OLD.상품코드;
	END;

DELETE FROM 입고
	WHERE 상품코드='a001'
		AND 입고일자='2023-06-16';
	
SELECT *
	FROM 상품;

SELECT *
	FROM 입고;
	
UPDATE 상품 SET 재고수량=0 WHERE 상품코드='a001';